Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
